version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: virtualenv
    versions:
    - 20.4.0
    - 20.4.1
    - 20.4.2
    - 20.4.3
  - dependency-name: tox
    versions:
    - 3.21.2
    - 3.21.3
    - 3.21.4
    - 3.22.0
  - dependency-name: jinja2
    versions:
    - 2.11.2
